version: '3'

services:
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - 6379
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/project
    ports:
      - '3000:3000'
    depends_on:
      - redis

volumes:
  redis:
